#func_print_heading "Copy MongoDB Repo file"
#cp ${script_path}/mongo.repo /etc/yum.repos.d/mongo.repo
#func_print_heading "Installing MongoDB Client"
#dnf install mongodb-org-shell -y
#func_print_heading "Loading Schema"
#mongo --host mongod-dev.kruthikadevops.online	</app/schema/${component_name}.js
- name: Load MongoDB Schema
  when: schema_setup == "mongo"
  block:
    - name: Copy MongoDB repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed
    - name: Load MySQL Schema
      ansible.builtin.shell: mongo --host mongod-dev.kruthikadevops.online	</app/schema/{{component}.js

