#func_print_heading "Installing maven"
#dnf install maven -y
#func_stat_check $?
#func_prereq


#func_print_heading "Mvn operations"
#mvn clean package
#mv target/${component_name}-1.0.jar ${component_name}.jar

#func_print_heading "Installing mysql"
#dnf install mysql -y
#func_print_heading "loading schema"
#mysql -h mysql-dev.kruthikadevops.online -uroot -p${mysql_root_password} < /app/schema/${component_name}.sql
#func_print_heading "Staring shipping service"
#func_systemd

- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: installed
- name: Include task list in play
  ansible.builtin.import_tasks:
    file: app_prereq.yml
- name: perform maven operations
  ansible.builtin.shell: mvn clean package; mv target/${component_name}-1.0.jar ${component_name}.jar
  args:
    chdir: /app
- name: load Sql schema
  ansible.builtin.import_tasks:
    file: schema_setup.yml
- name: Include SystemD
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
